<a href="https://colab.research.google.com/github/orlandxrf/curso-dl/blob/main/notebooks/NeuronaArtificial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problema
---
Problema: El fin de semana vas a ver el final de tu serie favorita de `Netflix`, para ello tienes planeado comer `nachos` con mucho queso. Además tienes que `estudiar` para `aprobar` el examen parcial de Aprendizaje Profundo del día lunes. Lo que se desea es que la neurona nos indique el posible resultado (salida) de $Y$ dadas las entradas $X$.<br>
<br>
$X_{1} = \{0, 1\};$ $1$ si ves tu serie, $0$ si no la ves<br>
$X_{2} = \{0, 1\};$ $1$ comes nachos, $0$ no hay nachos<br>
$X_{3} = \{0, 1\};$ $1$ estudias para el examen, $0$ no estudias para el examen<br>
<br>
$Y_{1}= \{0: reprobar, 1:aprobar\}$<br>
<br>
Para calcular la salida, el umbral definido esta dado bajo las siguientes condiciones:<br>
<br>
$output = \begin{cases} 0, & \text{si } \Sigma_{i}w_{i}X_{i} \leq 5\\ 1, & \text{si } \Sigma_{i}w_{i}X_{i} > 5 \end{cases}$<br>



In [1]:

def umbral(z):
    if z > 4.0:
        return 1.0
    else:
        return 0.0

def neurona(x, w):
    z = 0
    for i in range(len(x)):
        z += x[i] * w[i] # w1 * X1 + w2 * X2 + w3 * X3
    a = umbral(z)
    return a

# definimos los valores de entrada
X = [#  X1,  X2,  X3
        [0, 0, 0],
        [1, 0, 0],
        [0, 1, 0],
        [1, 1, 0],
        [0, 0, 1],
        [1, 0, 1],
        [0, 1, 1],
        [1, 1, 1],
]

# se establece la prioridad que le damos a cada entrada (pesos)
w = [
    3, # quiero ver el final de la serie de
    1, # no importa si no hay nachos para comer
    5, # el examen es mi prioridad
]

print ('-'*35)
print (f"{'X1':10}{'X2':10}{'X3':10}Y")
print ('-'*35)

for i in range(len(X)):
    Y = neurona(X[i], w)
    print (f"{X[i][0]:0}{X[i][1]:10}{X[i][2]:10}{int(Y):10}")

labels = {0:'NO', 1:'SI'}

print ('-'*42)
print (f"{'Netflix':12}{'nachos':10}{'estudiar':12}aprobar")
print ('-'*42)

for i in range(len(X)):
    Y = neurona(X[i], w)
    print (f"{labels[X[i][0]]:12}{labels[X[i][1]]:12}{labels[X[i][2]]:12}{labels[int(Y)]}")


-----------------------------------
X1        X2        X3        Y
-----------------------------------
0         0         0         0
1         0         0         0
0         1         0         0
1         1         0         0
0         0         1         1
1         0         1         1
0         1         1         1
1         1         1         1
------------------------------------------
Netflix     nachos    estudiar    aprobar
------------------------------------------
NO          NO          NO          NO
SI          NO          NO          NO
NO          SI          NO          NO
SI          SI          NO          NO
NO          NO          SI          SI
SI          NO          SI          SI
NO          SI          SI          SI
SI          SI          SI          SI


# Neurona Artificial
---

La neurona artificial es un modelo simplificado de la neurona natural, la cual trata de imitar 3 aspectos principales:

*   La fuerza sináptica que pondera los impulsos recibidos
*   La acumulación de estos impulsos ponderados
*   La activación de la neurona que produce un impulso de respuesta a su salid

La primera neurona artificial fue la llamada Unidad de Umbral Lineal, propuesta en 1943 por Warren McCulloch y Walter Pitts, la cual presupone que tanto los valores de los atributos de entrada como los valores de salida son binarios.

## Unidad de Umbral Lineal
La operación que lleva a cabo una neurona artificial está dada por la suma pesada evaluada en una función de activación $\phi$. Una de las primeras funciones de activación utilizadas fue la **escalón unitario**, definida como:<br>
<br>
$\phi(x) = \begin{cases} 1, & \text{si } x \geq 0\\0, & \text{en caso contrario}\end{cases}$<br>
<br>
Esta se puede llevar a cabo con la siguiente función de Python:

In [8]:
import numpy as np

def funcion_escalon(z):
  if z >= 0.0:
    return 1.0
  else:
    return 0.0

La suma pesada simplemente consiste en multiplicar cada entrada por su correspondiente peso y sumarle el sesgo. Esto lo podemos expresar como:<br>
<br>
$z = w_1 \cdot x_1 + w_2 \cdot x_2 + \cdots + w_d \cdot x_d + b$<br>
<br>
En su forma vectorial:<br>
<br>
$z = \mathbf{w}^T \mathbf{x} + b$<br>
<br>
Para realizar esto en Python, podemos usar la función `dot` de `numpy` de la siguiente manera `z = np.dot(w.T, x) + b`. Así, la operación de la neurona completa sería:

In [10]:
import numpy as np

def neurona(x, w, b):
  z = np.dot(w.T, x) + b
  a = funcion_escalon(z)

  return a

## Neurona Artificial para calcular la operación lógica OR ($\lor$)
La tabla de verdad de la operación lógica OR es la siguiente:<br>

| $x_1$ | $x_2$ | $y$
| ----- | :----:| :--:|
|0 |0 | 0 |
|0 |1 | 1 |
|1 |0 | 1 |
|1 |1 | 1 |

Donde $y=x_1 \lor x_2$. La neurona recibe 2 valores binarios como entrada y produce un valor binario como salida. Lo que se desea calcular es:<br>
<br>
$\hat{y} = \phi(w_1 \cdot x_1 + w_2 \cdot x_2 + b)$<br>
<br>
Los posibles valores para aproximar la operación OR son: $w_{1}=3$, $w_{2}=4$ y $b=-2$.

In [30]:
# valores de X1 y X2
X = np.array([
  [0., 0.],
  [0., 1.],
  [1., 0.],
  [1., 1.]
])

# establecer los pesos de w1 y w2
w = np.array([3, 4]).T # la matriz transpuesta de los pesos

# definir el bias
b = -2

print ('-'*21)
print (f"{'X1':8}{'X2':8}{'y_hat':8}")
print ('-'*21)

for i in range(X.shape[0]): # X.shape = (4, 2)
    y_hat = neurona(X[i, :], w, b)
    # print ('{0} \t{1}\t{2}'.format(X[i, 0], X[i, 1], y_hat))
    print (f"{X[i,0]:0}{X[i,1]:8}{y_hat:8}")


---------------------
X1      X2      y_hat   
---------------------
0.0     0.0     0.0
0.0     1.0     1.0
1.0     0.0     1.0
1.0     1.0     1.0


## **Ejercicio**: Función lógica AND y NAND
Tabla de verdad de la función lógica AND ($\land$):<br>

| $x_1$ | $x_2$ | $y$
| ----- | :----:| :--:|
|0 |0 | 0 |
|0 |1 | 0 |
|1 |0 | 0 |
|1 |1 | 1 |

Tabla de verdad de la función lógica NAND:<br>

| $x_1$ | $x_2$ | $y$
| ----- | :----:| :--:|
|0 |0 | 1 |
|0 |1 | 1 |
|1 |0 | 1 |
|1 |1 | 0 |

Encuentre los valores para $w_1$, $w_2$ y $b$ para cada una de las funciones lógicas.

In [ ]:
# escriba aquí sus soluciones para las funciones AND y NAND

# Perceptron

In [32]:
def perceptron(X, y, n_epochs = 10):
  w = np.zeros(X.shape[1]) # pesos
  b = 0 # bias
  for i in range(n_epochs):
    suma_error = 0.0
    for j in range(X.shape[0]):
      y_hat = neurona(X[j], w, b)
      
      # se calcula el "error" entre la salida real actual "y[j]" y la salida objetivo "y_hat".
      error = y[j] - y_hat

      # sumar el error al peso actual
      w += error * X[j]
      # sumar el error al bias actual
      b += error
      
      # sumatoria de los errores
      suma_error += np.abs(error)

    print(f"Epoch {i}/{n_epochs} error: {suma_error / float(X.shape[0])}")

  return w, b

### Aproximando la función lógica OR ($\lor$)


In [39]:
# valores de X1 y X2
X = np.array([
  [0., 0.],
  [0., 1.],
  [1., 0.],
  [1., 1.],
])

# valor esperado 
y_or = np.array([
  0.,
  1.,
  1.,
  1.,
]) 

# llamar función perceptrón para aproximar los valores
w, b = perceptron(X, y_or, n_epochs=10)

Epoch 0/10 error: 0.5
Epoch 1/10 error: 0.5
Epoch 2/10 error: 0.25
Epoch 3/10 error: 0.0
Epoch 4/10 error: 0.0
Epoch 5/10 error: 0.0
Epoch 6/10 error: 0.0
Epoch 7/10 error: 0.0
Epoch 8/10 error: 0.0
Epoch 9/10 error: 0.0


In [44]:
# mostrar los pesos identificados
print (f"w1:\t{w[0]}\nw1:\t{w[1]}\nb:\t{b}")

w1:	1.0
w1:	1.0
b:	-1.0


In [45]:
# verificar valores
# utilizar los valores aprendidos con la neurona artificial
print ('-'*21)
print (f"{'X1':8}{'X2':8}{'y_hat':8}")
print ('-'*21)

for i in range(X.shape[0]): # X.shape = (4, 2)
    y_hat = neurona(X[i, :], w, b)
    # print ('{0} \t{1}\t{2}'.format(X[i, 0], X[i, 1], y_hat))
    print (f"{X[i,0]:0}{X[i,1]:8}{y_hat:8}")

---------------------
X1      X2      y_hat   
---------------------
0.0     0.0     0.0
0.0     1.0     1.0
1.0     0.0     1.0
1.0     1.0     1.0


### Aproximando la función lógica AND

In [58]:
# los valores de X1 y X2 no cambian
print (X)

# definir valores esperados para AND
y_and = np.array([
  0.,
  0.,
  0.,
  1.,
])

# llamar perceptron para aproximar los valores
w, b = perceptron(X, y_and, n_epochs=10)

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Epoch 0/10 error: 0.5
Epoch 1/10 error: 0.75
Epoch 2/10 error: 0.75
Epoch 3/10 error: 0.5
Epoch 4/10 error: 0.25
Epoch 5/10 error: 0.0
Epoch 6/10 error: 0.0
Epoch 7/10 error: 0.0
Epoch 8/10 error: 0.0
Epoch 9/10 error: 0.0


In [59]:
# mostrar los pesos identificados para aproximar los valores de AND
print (f"w1:\t{w[0]}\nw1:\t{w[1]}\nb:\t{b}")

w1:	2.0
w1:	1.0
b:	-3.0


In [60]:
# verificar valores
# utilizar los valores aprendidos con la neurona artificial
print ('-'*21)
print (f"{'X1':8}{'X2':8}{'y_hat':8}")
print ('-'*21)

for i in range(X.shape[0]): # X.shape = (4, 2)
    y_hat = neurona(X[i, :], w, b)
    # print ('{0} \t{1}\t{2}'.format(X[i, 0], X[i, 1], y_hat))
    print (f"{X[i,0]:0}{X[i,1]:8}{y_hat:8}")

---------------------
X1      X2      y_hat   
---------------------
0.0     0.0     0.0
0.0     1.0     0.0
1.0     0.0     0.0
1.0     1.0     1.0


### Aproximando la función lógica NAND

In [61]:
# los valores de X1 y X2 no cambian
print (X)

# definir valores esperados para NAND
y_and = np.array([
  1.,
  1.,
  1.,
  0.,
])

# llamar perceptron para aproximar los valores
w, b = perceptron(X, y_and, n_epochs=10)

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Epoch 0/10 error: 0.25
Epoch 1/10 error: 0.75
Epoch 2/10 error: 0.75
Epoch 3/10 error: 0.5
Epoch 4/10 error: 0.25
Epoch 5/10 error: 0.0
Epoch 6/10 error: 0.0
Epoch 7/10 error: 0.0
Epoch 8/10 error: 0.0
Epoch 9/10 error: 0.0


In [62]:
# mostrar los pesos identificados para aproximar los valores de NAND
print (f"w1:\t{w[0]}\nw1:\t{w[1]}\nb:\t{b}")

w1:	-2.0
w1:	-1.0
b:	2.0


In [63]:
# verificar valores
# utilizar los valores aprendidos con la neurona artificial
print ('-'*21)
print (f"{'X1':8}{'X2':8}{'y_hat':8}")
print ('-'*21)

for i in range(X.shape[0]): # X.shape = (4, 2)
    y_hat = neurona(X[i, :], w, b)
    # print ('{0} \t{1}\t{2}'.format(X[i, 0], X[i, 1], y_hat))
    print (f"{X[i,0]:0}{X[i,1]:8}{y_hat:8}")

---------------------
X1      X2      y_hat   
---------------------
0.0     0.0     1.0
0.0     1.0     1.0
1.0     0.0     1.0
1.0     1.0     0.0


---
# Tarea 1

* Del problema descrito al inicio del notebook, aproximar sus valores con lo aprendido hasta ahora.
* Escribir un documento con su propuesta con resultados (pueden utilizar capturas de pantalla)  con su nombre y número de cuenta
* Enviar de forma electrónica al correo de contacto
---



## Aproximación de funciones no lineales: XOR($\oplus$)

Minsky y Papert mostraron que una neurona LTU (Threshold Logic Unit) o LTU (Linear Threshold Unit) no puede aproximar de forma precisa una función no lineal como la compuerta XOR ():

| $x_1$ | $x_2$ | $y$
| ----- | :----:| :--:|
|0 |0 | 0 |
|0 |1 | 1 |
|1 |0 | 1 |
|1 |1 | 0 |

Sin embargo, es posible aproximar este tipo combinando múltiples LTU conectadas en red. Por ejemplo, es posible llevar a cabo la operación XOR con operaciones OR, AND y NAND:<br>
<br>
$x_1 \mathbin{\oplus} x_2 = (x_1 \lor x_2) \land \neg(x_1 \land x_2)$<br>
<br>
Se define en el siguiente método:

In [82]:
def multicapa(x, W1, b1, W2, b2):
  # np.vectorize = define una función vectorizada que toma una secuencia anidada de objetos o matrices numpy como entradas
  # y devuelva una sola matriz numpy o una tupla de matrices numpy
  escalon_vectorial = np.vectorize(funcion_escalon)
  
  # realiza la multiplicación de las entradas de X1 y X2 con los pesos definidos en W1 y suma el bias
  a = escalon_vectorial(np.dot(W1.T, x) + b1)

  #finalmente regresa la multiplicación de los pesos definidos en W2 con el resultado de la multiplicación anterior y suma el bias
  return escalon_vectorial(np.dot(W2.T, a) + b2)

Encontrando los valores de pesos y sesgos adecuados, podemos usar esta función para aproximar la operación XOR. Previamente, ya se han encontrado los pesos y sesgos para las operaciones OR, AND y NAND, por lo que podemos usar estas neuronas con sus correspondientes pesos y sesgos.<br>
<br>
La red tendría 2 neuronas conectadas a las entradas que realizan las operaciones OR ($w_{11}^{\{1\}} = 10$, $w_{12}^{\{1\}} = 10$ y $b_1^{\{1\}} = -5$) y NAND ($w_{21}^{\{1\}} = -10$, $w_{22}^{\{1\}} = -10$ y $b_2^{\{1\}} = 15$) respectivamente.<br>
<br>
La salida de estas 2 neuronas estarían conectadas a una tercera neurona que realiza la operacioón AND ($w_{11}^{\{2\}} = 10$, $w_{12}^{\{2\}} = 10$ y $b_1^{\{2\}} = -15$).<br>
<br>
En su forma matricial:<br>

$\mathbf{W}^{\{1\}} = \begin{bmatrix} 10 & -10\\, 10 & -10, \\ \end{bmatrix}$

$\mathbf{b}^{\{1\}} = \begin{bmatrix} -5 & 15 \end{bmatrix}$

$\mathbf{W}^{\{2\}} = \begin{bmatrix} 10\\ 10 \end{bmatrix}$

$\mathbf{b}^{\{2\}} = \begin{bmatrix} -15 \end{bmatrix}$


In [83]:
# los valores de X1 y X2 siguen siendo los mismos
print (f"{X}\n")

# establecer los valores esperados
y_xor = np.array([0., 1., 1., 0.])

# establecer los pesos de OR y NAND, así como su bias respectivamente
W1 = np.array([[10, -10], [10, -10]])
b1 = np.array([-5, 15])

# establecer los pesos de AND y su bias
W2 = np.array([[10], [10]])
b2 = np.array([-15])

print(f'W1:\t[{W1[0,:]}{W1[1,:]}]\nb1:\t{b1}\n')
print(f'W2:\t[{W2[0]}{W2[1]}]\nb_2:\t{b2}\n')


print('-'*29)
print(f"{'x1':8}{'x2':8}{'y':8}{'y_hat':8}")
print('-'*29)

for i in range(X.shape[0]): # X.shape = (4, 2)
  y_hat = multicapa(X[i], W1, b1, W2, b2)
  print(f"{X[i, 0]}{X[i, 1]:8}{y_xor[i]:8}{y_hat[0]:8}")

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]

W1:	[[ 10 -10][ 10 -10]]
b1:	[-5 15]

W2:	[[10][10]]
b_2:	[-15]

-----------------------------
x1      x2      y       y_hat   
-----------------------------
0.0     0.0     0.0     0.0
0.0     1.0     1.0     1.0
1.0     0.0     1.0     1.0
1.0     1.0     0.0     0.0
